import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.EXPO_PUBLIC_SUPABASE_URL || 'https://gvcxbhbnsocvvngncyyy.databasepad.com';
const SUPABASE_ANON_KEY = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjVjM2VmM2M3LWIyNjItNDNhMy05NmY5LWQxYzYzODI0ZTk0MSJ9.eyJwcm9qZWN0SWQiOiJndmN4YmhibnNvY3Z2bmduY3l5eSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzgxNTA1MDY3LCJleHAiOjIwOTU4NjUwNjcsImlzcyI6ImZhbW91cy5kYXRhYmFzZXBhZCIsImF1ZCI6ImZhbW91cy5jbGllbnRzIn0._d6_6KSZFoSDP9cFEqiwLtDLLEbzIdeIx6e-2cPWqgA';

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
